language: java
addons:
  chrome: stable
install:
- wget https://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip
- mkdir chromedriver
- unzip chromedriver_linux64.zip -d chromedriver
- export PATH=$PATH:$PWD/chromedriver
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
